- name: Allow usage of privileged ports by rootless processes
  ansible.builtin.import_role:
    name: podman
    tasks_from: rootless_ports
- name: Volumes configuration
  ansible.builtin.include_tasks: volumes.yml
- name: Copy configuration files
  ansible.builtin.include_tasks: config.yml
- name: Build Caddy image
  ansible.builtin.include_tasks: images.yml
- name: Quadlet files configuration
  ansible.builtin.include_tasks: quadlets.yml
- name: Services configuration
  ansible.builtin.include_tasks: services.yml
