---
- name: Create Oauth2-Proxy Quadlet file
  become: true
  become_user: '{{ oauth2_proxy_user }}'
  notify: Restart Oauth2-Proxy
  containers.podman.podman_container:
    name: '{{ oauth2_proxy_container }}'
    image: quay.io/oauth2-proxy/oauth2-proxy
    state: quadlet
    quadlet_filename: '{{ oauth2_proxy_container }}'
    ports:
      - '{{ oauth2_proxy_port | default("4180") }}:4180'
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: '{{ tz }}'
      OAUTH2_PROXY_HTTP_ADDRESS: '{{ oauth2_proxy_http_address | default("0.0.0.0:4180") }}'
      OAUTH2_PROXY_EMAIL_DOMAINS: '{{ oauth2_proxy_email_domains }}'
      OAUTH2_PROXY_REVERSE_PROXY: '{{ oauth2_proxy_reverse }}'
      OAUTH2_PROXY_COOKIE_SECRET: '{{ oauth2_proxy_cookie_secret }}'
      OAUTH2_PROXY_COOKIE_DOMAINS: '{{ oauth2_proxy_cookie_domains }}'
      OAUTH2_PROXY_WHITELIST_DOMAINS: '{{ oauth2_proxy_whitelist_domains }}'
      OAUTH2_PROXY_PROVIDER: '{{ oauth2_proxy_provider }}'
      OAUTH2_PROXY_CLIENT_ID: '{{ oauth2_proxy_client_id }}'
      OAUTH2_PROXY_CLIENT_SECRET: '{{ oauth2_proxy_client_secret }}'
      OAUTH2_PROXY_REDIRECT_URL: '{{ oauth2_proxy_redirect_url }}'
      OAUTH2_PROXY_OIDC_ISSUER_URL: '{{ oauth2_proxy_oidc_url }}'
      OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL: '{{ oauth2_proxy_allow_unverified_email }}'
      OAUTH2_PROXY_REQUEST_LOGGING: 'true'
      OAUTH2_PROXY_AUTH_LOGGING: 'true'
      OAUTH2_PROXY_STANDARD_LOGGING: 'true'
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
    quadlet_options:
      - 'AutoUpdate=registry'
      - 'Pull=newer'
      - |
        [Service]
        Restart=always
      - |
        [Install]
        WantedBy=default.target multi-user.target
