---
- name: Create Guacamole web Quadlet file
  become: true
  become_user: '{{ guacamole_web_user }}'
  notify: Restart Guacamole web
  containers.podman.podman_container:
    name: '{{ guacamole_web_container }}'
    image: docker.io/guacamole/guacamole:latest
    state: quadlet
    quadlet_filename: '{{ guacamole_web_container }}'
    ports:
      - '{{ guacamole_web_port | default(8080) }}:8080'
    network: '{{ guacamole_web_network | default(omit) }}'
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: '{{ tz }}'
      GUACD_HOSTNAME: '{{ guacamole_web_guacd_hostname }}'
      GUACD_PORT: '{{ guacamole_web_guacd_port | default(4822) }}'
      POSTGRESQL_HOSTNAME: '{{ guacamole_web_pg_host | default(omit) }}'
      POSTGRESQL_DATABASE: '{{ guacamole_web_pg_db | default(omit) }}'
      POSTGRESQL_PORT: '{{ guacamole_web_pg_port | default(omit) }}'
      POSTGRESQL_USER: '{{ guacamole_web_pg_user | default(omit) }}'
      POSTGRESQL_PASSWORD: '{{ guacamole_web_pg_pass | default(omit) }}'
      EXTENSION_PRIORITY: '{{ guacamole_web_extension_priority | default(omit) }}'
      OPENID_AUTHORIZATION_ENDPOINT: '{{ guacamole_web_openid_authorization_endpoint | default(omit) }}'
      OPENID_JWKS_ENDPOINT: '{{ guacamole_web_openid_jwks_endpoint | default(omit) }}'
      OPENID_ISSUER: '{{ guacamole_web_openid_issuer | default(omit) }}'
      OPENID_CLIENT_ID: '{{ guacamole_web_openid_client_id | default(omit) }}'
      OPENID_REDIRECT_URI: '{{ guacamole_web_openid_redirect_uri | default(omit) }}'
      WEBAPP_CONTEXT: 'ROOT'
      LOG_LEVEL: 'debug'
    quadlet_options:
      - 'AutoUpdate=registry'
      - 'Pull=newer'
      - |
        [Install]
        WantedBy=default.target multi-user.target
