---
- name: Install packages
  ansible.builtin.import_tasks: packages.yml

- name: Podman configuration
  ansible.builtin.import_role:
    name: podman

- name: Configure performance options
  ansible.builtin.import_tasks: performance.yml

- name: Kernel modules configuration
  ansible.builtin.import_tasks: modules.yml

- name: Ensure qemu-guest-agent is running and starts on boot
  become: true
  ansible.builtin.systemd_service:
    state: started
    name: qemu-guest-agent

- name: Ensure SELinux is present and configured
  ansible.builtin.import_tasks: selinux.yml
