---
- name: VPS setup
  import_playbook: vps.yml
- name: Bastion setup
  import_playbook: bastion.yml
- name: Public DNS setup
  import_playbook: public_dns.yml
- name: Hypervisor setup
  import_playbook: hypervisor.yml
- name: Virtual machines DNS server deployment
  import_playbook: vm_dns.yml
- name: Zram configuration
  import_playbook: zram.yml
- name: Virtual machines configuration
  import_playbook: vm.yml
- name: NAS deployment
  import_playbook: nas.yml
- name: Security services deployment
  import_playbook: security.yml
- name: Knowledge management deployment
  import_playbook: knowledge.yml
- name: Torrent deployment
  import_playbook: torrent.yml
- name: Servarr deployment
  import_playbook: servarr.yml
- name: Streaming deployment
  import_playbook: streaming.yml
- name: VMWare host deployment
  import_playbook: vmware.yml
- name: Reverse proxy deployment
  import_playbook: reverse_proxy.yml
