- name: Configure Virtual Private Server
  hosts: vps
  vars:
    vps_user: 'vps-hetzner'

  tasks:

    - name: Deploy Headscale control server
      ansible.builtin.import_role:
        name: headscale
      vars:
        headscale_user: '{{ vps_user }}'
        headscale_container: 'headscale'
        headscale_command: 'serve'
        headscale_http_port: '8080'
        headscale_metrics_port: '9090'
        headscale_dns_server: '100.64.0.6'
        headscale_conf_dir: '/var/headscale'
        headscale_tls_vol: 'headscale_tls'
        headscale_network: 'host'
        headscale_server_host: '{{ vpn_host }}.{{ internet_host }}'
        headscale_server_port: '443'
        headscale_listen_host: '0.0.0.0'
        headscale_listen_port: '8080'
        headscale_metrics_host: '0.0.0.0'
        headscale_grpc_listen_addr: '0.0.0.0'
        headscale_grpc_listen_port: '50443'
        headscale_dns_base_domain: 'nodes.{{ vpn_host }}.{{ internet_host }}'

    - name: Deploy internet facing Caddy
      ansible.builtin.import_role:
        name: caddy
      vars:
        caddy_user: '{{ vps_user }}'
        caddy_opt: caddy_opt
        caddy_tls: caddy_tls
        caddy_conf: /etc/Caddyfile
        caddy_internet_facing: true
        caddy_extensions:
          - github.com/corazawaf/coraza-caddy/v2
          - github.com/tailscale/caddy-tailscale

        caddy_image: 'caddy-public'
        caddy_networks: 'host'
        caddy_ts_authkey: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66306264363131333637336665343933393436333836666335313137633164386237336163333232
          6465653062326437303738373661326530643261663963610a313463376130353566373836613238
          36643962363330336538353465303531323331373134653837336162383035303335346431636164
          3939633333336165390a653636666439363430636635616664343534326330656431666632313437
          37396663653039343864376639383261663133376263636333656163393034373533656635383066
          66666566653136313033396462663761373664656531333838353539313437613564373638623131
          333664366262386562633162656464653461

    - name: Deploy Blocky DNS Server
      ansible.builtin.import_role:
        name: blocky
      vars:
        blocky_user: '{{ vm_dns_user }}'
        blocky_container: 'blocky'
        blocky_config_dir: '/var/blocky'
        blocky_dns_port: '53'
        blocky_http_port: '4000'
        blocky_upstreams:
          - '1.1.1.1'
          - '8.8.8.8'
        blocky_adlists:
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/pro.plus.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/fake.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/popupads.txt'
        blocky_security_lists:
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/tif.txt'
          # - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/doh-vpn-proxy-bypass.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/dyndns.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/hoster.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/gambling.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/tif.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/dyndns.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/hoster.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/gambling.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.amazon.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.apple.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.huawei.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.winoffice.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.samsung.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.tiktok.extended.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.lgwebos.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.roku.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.vivo.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.oppo-realme-onlydomains.txt'
          - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/native.xiaomi.txt'
