---
- name: Bind mounts configuration
  ansible.builtin.import_tasks: directories.yml
- name: Volume configuration
  ansible.builtin.import_tasks: volumes.yml
- name: Quadlet files configuration
  ansible.builtin.include_tasks: quadlets.yml
- name: Services configuration
  ansible.builtin.include_tasks: services.yml
